mybatis:
  type-aliases-package:
    com.example.demo
  mapper-locations:
    classpath:mapping/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver

